### ISSUE TITLE
Add sanity checks for yaml

### ISSUE THREAD

**Issue by selama1** [dreamproit/kosher-dill#12]
Add some sanity checks for the yaml file before running it, to avoid some pitfalls.

So far, I have found three checks we would like to have:
1. Check if expected and actual (both for stdout and stderr) have different "treat_as". For example, `stdout` is plain text and `expected_stdout` is json. This should not be allowed.
2. Report when the same test name is used in two or more tests in the same yaml file.
3. Make it an error when the `file_path` for either `stdout` or `stderr` are the same in different place (either the same test or between different tests). The reason we save actual results is to keep track of them and be able to debug failures. I believe we should not overwrite these within the same file.

We would add more checks to this list in the future, when we see more issues.

**Comment by BorodaUA** [comment]
Hi @selama1 we managed to implement changes that you asked. Now we will raise more verbose exceptions when our .yaml files improperly configured.

**Comment by aih** [comment]
I'm re-assigning to Sela for testing.
