### ISSUE TITLE
Improve logging of input test or provide debugging options

### ISSUE THREAD

**Issue by aih** [dreamproit/kosher-dill#16]
Here, there is an 'attribute error' parsing some part of the yaml input, but it is not clear where the error is in the yaml.
<img width="772" alt="image" src="https://user-images.githubusercontent.com/217356/188036709-5f441d87-7736-4a81-986f-65320d85156e.png">

**Comment by alexbojko** [comment]
@aih could you provide us with the test yaml file which produced such an error?

@BorodaUA seems like the problem with the skipping JSON path if path leads into the list. Could you please check such a case:

data:
```json
{"a": [{"b": 1}, {"c": 2}]}
```

and we should skip path:
```
a.0.b
```

I thought we had such test case in our self_tests directory. Aren't we?

**Comment by aih** [comment]
Unfortunately, I deleted the branch where I had the yaml. I added a check that `local_data` is an object before using `get`, but we may want to add types so that we can catch these issues earlier?

**Comment by BorodaUA** [comment]
Hi team 👋 
@alexbojko I've looked into our skips, we can skip element in list with no problem, also we can skip in nested lists, and yes we have running test to check that.
@aih We will need steps to reproduce to find the issue, as of right now it is not clear how to find the error.

**Comment by aih** [comment]
I'll close for now and will reopen or open a new issue if we see this again.
